name: Test Pose Estimator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
      
    steps:
    - uses: actions/checkout@v4
      
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y python3-pip python3-pytest python3-pytest-cov
        pip install opencv-python numpy scipy
        
    - name: Build
      run: |
        . /opt/ros/humble/setup.sh
        colcon build --packages-select ibpc_pose_estimator_py
        
    - name: Test
      run: |
        . /opt/ros/humble/setup.sh
        . install/setup.sh
        colcon test --packages-select ibpc_pose_estimator_py --event-handlers console_direct+
        colcon test-result --verbose 